### ISSUE TITLE
Does Scrapling offer JavaScript support like Requests-HTML?

### ISSUE THREAD

**Issue by araichev** [D4Vinci/Scrapling#2]
I can't find an answer to this in the documentation.

**Comment by D4Vinci** [comment]
Scrapling currently only working as a parsing engine for web pages so you have to load the pages somehow then pass the source to it.
But starting from next version, Scrapling will have its browser to load JS and everything automatically for you starting with the URL only.

Stay tuned it will be released this week most likely or the following week at most!

**Comment by D4Vinci** [comment]
@araichev  The new version was released days ago but I forgot to update here
