### ISSUE TITLE
No module named 'scrapling.default'

### ISSUE THREAD

**Issue by ibrahimmudassar** [D4Vinci/Scrapling#20]
### Have you searched if there an existing issue for this?

- [X] I have searched the existing issues

### Python version (python --version)

Python 3.11.0

### Scrapling version (scrapling.__version__)

0.2.7

### Dependencies version (pip3 freeze)

agate==1.7.0                                                                                      
aiofiles==24.1.0                                                                                  
aiohttp==3.9.1                                                                                    
aiohttp-retry==2.8.3                                                                              
aiohttp-socks==0.8.4                                                                              
aiometer==0.5.0                                                                                   
aioquic==1.2.0                                                                                    
aiosignal==1.3.1                                                                                  
annotated-types==0.6.0                                                                            
anyio==4.2.0                                                                                      
appdirs==1.4.4                                                                                    
arrow==1.3.0                                                                                      
asgiref==3.8.1                                                                                    
asttokens==2.4.0                                                                                  
async-property==0.2.2                                                                             
async-timeout==4.0.3                                                                              
attrs==23.1.0                                                                                     
Authlib==1.3.2                                                                                    
azure-core==1.31.0                                                                                
azure-storage-blob==12.13.0                                                                       
babel==2.16.0                                                                                     
backcall==0.2.0                                                                                   
bcrypt==4.2.0                                                                                     
beautifulsoup4==4.12.2                                                                            
betterproto==1.2.5                                                                                
bleach==6.1.0                                                                                     
blinker==1.7.0                                                                                    
boto3==1.26.165                                                                                   
botocore==1.29.165                                                                                
boxsdk==2.10.0                                                                                    
braintree==4.17.1                                                                                 
Brotli==1.1.0                                                                                     
browser-cookie3==0.19.1                                                                           
browserforge==1.1.2                                                                               
bs4==0.0.1                                                                                        
cachetools==5.5.0                                                                                 
cairocffi==1.6.1                                                                                  
CairoSVG==2.7.1                                                                                   
camoufox==0.4.4                                                                                   
cattrs==23.2.1                                                                                    
censusgeocode==0.4.3.post1                                                                        
certifi==2024.8.30                                                                                
cffi==1.16.0                                                                                      
chardet==5.2.0                                                                                    
charset-normalizer==3.3.1                                                                         
chromedriver-autoinstaller==0.6.4                                                                 
civis==1.16.1                                                                                     
click==8.1.3                                                                                      
cloudpickle==2.2.1                                                                                
colorama==0.4.6                                                                                   
colorthief==0.2.1                                                                                 
comm==0.1.4                                                                                       
contourpy==1.2.0                                                                                  
cryptography==43.0.0                                                                              
cssselect==1.2.0                                                                                  
cssselect2==0.7.0                                                                                 
curl_cffi==0.7.1                                                                                  
curlify==2.2.1                                                                                    
cycler==0.12.1                                                                                    
dbt-core==1.4.9                                                                                   
dbt-extractor==0.4.1                                                                              
dbt-postgres==1.4.9                                                                               
dbt-redshift==1.4.0                                                                               
debugpy==1.7.0                                                                                    
decorator==5.1.1                                                                                  
defusedxml==0.7.1                                                                                 
Deprecated==1.2.14                                                                                
discord-webhook==1.3.0                                                                            
docopt==0.6.2                                                                                     
docutils==0.17.1                                                                                  
duckduckgo_search==4.5.0                                                                          
environs==9.5.0                                                                                   
ephem==4.1.5                                                                                      
et-xmlfile==1.1.0                                                                                 
executing==1.2.0                                                                                  
exrex==0.11.0                                                                                     
facebook-business==13.0.0                                                                         
fake-useragent==1.4.0                                                                             
Faker==26.0.0                                                                                     
fastapi==0.109.1                                                                                  
fastf1==3.1.5                                                                                     
fastjsonschema==2.19.1                                                                            
feedparser==6.0.11                                                                                
filelock==3.16.1                                                                                  
Flask==3.0.2                                                                                      
Flask-Cors==4.0.0                                                                                 
flask-localtunnel==1.0.7                                                                          
Flask-SQLAlchemy==3.1.1                                                                           
fonttools==4.45.0                                                                                 
frozenlist==1.4.1                                                                                 
future==1.0.0                                                                                     
fuzzywuzzy==0.18.0                                                                                
g4f==0.2.2.7                                                                                      
geographiclib==2.0                                                                                
geopy==2.4.1                                                                                      
gevent==24.2.1                                                                                    
google-api-core==2.20.0                                                                           
google-api-python-client==1.7.7                                                                   
google-auth==2.29.0                                                                               
google-auth-httplib2==0.2.0                                                                       
google-auth-oauthlib==1.2.1                                                                       
google-cloud-bigquery==3.23.1                                                                     
google-cloud-core==2.4.1                                                                          
google-cloud-storage==2.16.0                                                                      
google-cloud-storage-transfer==1.9.1                                                              
google-crc32c==1.6.0                                                                              
google-resumable-media==2.7.0                                                                     
googleapis-common-protos==1.65.0                                                                  
greenlet==3.1.1                                                                                   
grequests==0.7.0                                                                                  
grpcio==1.62.2                                                                                    
grpcio-status==1.62.2                                                                             
grpclib==0.4.7                                                                                    
gspread==3.7.0                                                                                    
h11==0.14.0                                                                                       
h2==4.1.0                                                                                         
hologram==0.0.16                                                                                  
hpack==4.0.0                                                                                      
html5lib==1.1                                                                                     
httpcore==1.0.6                                                                                   
httplib2==0.22.0                                                                                  
httpx==0.27.2                                                                                     
humanize==4.9.0                                                                                   
hyperframe==6.0.1                                                                                 
ics==0.7.2                                                                                        
idna==3.4                                                                                         
importlib-metadata==7.0.1                                                                         
inflection==0.5.1                                                                                 
iniconfig==2.0.0                                                                                  
ipykernel==6.25.2                                                                                 
ipython==8.12.3                                                                                   
isodate==0.6.1                                                                                    
itsdangerous==2.1.2                                                                               
jedi==0.19.0                                                                                      
jellyfish==0.11.2                                                                                 
Jinja2==3.1.2                                                                                     
jmespath==1.0.1                                                                                   
joblib==1.2.0                                                                                     
jsonref==0.2                                                                                      
jsonschema==4.21.1                                                                                
jsonschema-specifications==2023.12.1                                                              
jupyter_client==8.3.1                                                                             
jupyter_core==5.3.1                                                                               
jupyterlab_pygments==0.3.0                                                                        
kaitaistruct==0.10                                                                                
kaleido==0.2.1                                                                                    
kiwisolver==1.4.5                                                                                 
language-tags==1.2.0                                                                              
ldap3==2.9.1                                                                                      
leather==0.4.0                                                                                    
Levenshtein==0.24.0                                                                               
llvmlite==0.41.1                                                                                  
lml==0.1.0                                                                                        
Logbook==1.5.3                                                                                    
loguru==0.7.2                                                                                     
lxml==5.1.0                                                                                       
lz4==4.3.3                                                                                        
markdown-it-py==3.0.0                                                                             
MarkupSafe==2.1.5                                                                                 
marshmallow==3.20.1                                                                               
mashumaro==3.3.1                                                                                  
matplotlib==3.8.2                                                                                 
matplotlib-inline==0.1.6                                                                          
mdurl==0.1.2                                                                                      
minimal-snowplow-tracker==0.0.2                                                                   
mistune==3.0.2                                                                                    
mitmproxy==10.4.2                                                                                 
mitmproxy-windows==0.6.3                                                                          
mitmproxy_rs==0.6.3                                                                               
mmh3==4.1.0                                                                                       
msgpack==1.0.8                                                                                    
msrest==0.7.1                                                                                     
multidict==6.0.4                                                                                  
mysql-connector==2.2.9                                                                            
mysql-connector-python==8.0.18                                                                    
mysqlclient==2.2.4                                                                                
nbclient==0.9.0                                                                                   
nbconvert==7.16.2                                                                                 
nbformat==5.9.2                                                                                   
nest-asyncio==1.5.7                                                                               
networkx==2.8.8                                                                                   
newmode==0.1.6                                                                                    
numba==0.58.1                                                                                     
numpy==1.26.1                                                                                     
oauth2client==4.1.3                                                                               
oauthlib==3.2.2                                                                                   
openpyxl==3.0.10                                                                                  
openskill==5.1.1                                                                                  
orjson==3.10.12                                                                                   
outcome==1.3.0.post0                                                                              
packaging==23.1                                                                                   
pandas==2.0.3                                                                                     
pandocfilters==1.5.1                                                                              
paramiko==3.4.0                                                                                   
parse==1.20.1                                                                                     
parsedatetime==2.4                                                                                
parso==0.8.3                                                                                      
parsons==3.2.0                                                                                    
passlib==1.7.4                                                                                    
pathspec==0.10.3                                                                                  
petl==1.7.15                                                                                      
pickleshare==0.7.5                                                                                
Pillow==10.1.0                                                                                    
pip==24.3.1                                                                                       
pipreqs==0.5.0                                                                                    
platformdirs==3.10.0                                                                              
playwright==1.48.0                                                                                
plotly==5.17.0                                                                                    
pluggy==1.4.0                                                                                     
polars==0.19.16                                                                                   
prompt-toolkit==3.0.39                                                                            
proto-plus==1.24.0                                                                                
protobuf==4.25.5                                                                                  
psutil==5.9.5                                                                                     
psycopg2==2.9.9                                                                                   
psycopg2-binary==2.9.9                                                                            
publicsuffix2==2.20191221                                                                         
pure-eval==0.2.2                                                                                  
py-arkose-generator==0.0.0.2                                                                      
py-localtunnel==1.0.3                                                                             
pyairtable==2.3.3                                                                                 
pyarrow==14.0.1                                                                                   
pyasn1==0.6.0                                                                                     
pyasn1_modules==0.4.0                                                                             
pycountry==24.6.1                                                                                 
pycparser==2.21                                                                                   
pycryptodome==3.20.0                                                                              
pycryptodomex==3.20.0                                                                             
pydantic==2.6.0                                                                                   
pydantic_core==2.16.1                                                                             
pydivert==2.1.0                                                                                   
pyee==12.0.0                                                                                      
pyexcel==0.7.0                                                                                    
pyexcel-ezodf==0.3.4                                                                              
pyexcel-io==0.6.6                                                                                 
pyexcel-ods3==0.6.1                                                                               
pyexcel-xlsxw==0.6.1                                                                              
PyExecJS==1.5.1                                                                                   
PyGithub==1.51                                                                                    
Pygments==2.16.1                                                                                  
PyJWT==2.8.0                                                                                      
pylsqpack==0.3.18                                                                                 
PyNaCl==1.5.0                                                                                     
pyOpenSSL==24.2.1                                                                                 
pyparsing==3.1.1                                                                                  
pyperclip==1.9.0                                                                                  
pypiwin32==223                                                                                    
pyppeteer==1.0.2                                                                                  
pyquery==2.0.0                                                                                    
PySocks==1.7.1                                                                                    
pytest==7.4.4                                                                                     
pytest-base-url==2.1.0                                                                            
pytest-playwright==0.4.3                                                                          
pythermalcomfort==2.8.8                                                                           
python-dateutil==2.8.2                                                                            
python-dotenv==1.0.0                                                                              
python-Levenshtein==0.24.0                                                                        
python-slugify==8.0.3                                                                             
python-socks==2.4.4                                                                               
pytimeparse==1.1.8                                                                                
pytz==2023.3.post1                                                                                
pyusb==1.2.1                                                                                      
pywin32==306                                                                                      
PyYAML==6.0.2                                                                                     
pyzmq==25.1.1                                                                                     
rapidfuzz==3.5.2                                                                                  
rebrowser_playwright==1.48.100                                                                    
referencing==0.33.0                                                                               
requests==2.31.0                                                                                  
requests-cache==1.1.1                                                                             
requests-file==2.1.0                                                                              
requests-futures==1.0.1                                                                           
requests-html==0.10.0                                                                             
requests-oauthlib==1.3.0                                                                          
requests-toolbelt==0.10.1                                                                         
rich==13.9.4                                                                                      
rpds-py==0.18.0                                                                                   
rsa==4.9                                                                                          
ruamel.yaml==0.18.6                                                                               
ruamel.yaml.clib==0.2.8                                                                           
s3transfer==0.6.2                                                                                 
scipy==1.11.3                                                                                     
scrapling==0.2.7                                                                                  
screeninfo==0.8.1                                                                                 
selenium==4.25.0                                                                                  
selenium-wire==5.1.0                                                                              
service-identity==24.1.0                                                                          
setuptools==70.0.0                                                                                
sgmllib3k==1.0.0                                                                                  
simple-salesforce==1.11.6                                                                         
simplejson==3.16.0                                                                                
six==1.16.0                                                                                       
slackclient==1.3.0                                                                                
sniffio==1.3.0                                                                                    
sortedcontainers==2.4.0                                                                           
soupsieve==2.5                                                                                    
SQLAlchemy==1.4.54                                                                                
sqlalchemy-cockroachdb==2.0.2                                                                     
sqlparse==0.4.3                                                                                   
sshtunnel==0.4.0                                                                                  
stack-data==0.6.2                                                                                 
starlette==0.35.1                                                                                 
stem==1.8.2                                                                                       
stringcase==1.2.0                                                                                 
stripe==8.2.0                                                                                     
suds-py3==1.3.4.0                                                                                 
SurveyGizmo==1.2.3                                                                                
tabulate==0.9.0                                                                                   
TatSu==5.11.3                                                                                     
tenacity==8.2.3                                                                                   
text-unidecode==1.3                                                                               
texttable==1.7.0                                                                                  
thefuzz==0.20.0                                                                                   
timple==0.1.7                                                                                     
tinycss2==1.2.1                                                                                   
tldextract==5.1.3                                                                                 
tornado==6.4.1                                                                                    
torrequest==0.1.0                                                                                 
tqdm==4.66.1                                                                                      
traitlets==5.9.0                                                                                  
trio==0.24.0                                                                                      
trio-websocket==0.11.1                                                                            
twilio==8.2.1                                                                                     
types-python-dateutil==2.8.19.20240106                                                            
typing_extensions==4.9.0                                                                          
tzdata==2023.3                                                                                    
ua-parser==1.0.0                                                                                  
ua-parser-builtins==0.18.0                                                                        
undetected-chromedriver==3.5.5                                                                    
uritemplate==3.0.1                                                                                
url-normalize==1.4.3                                                                              
urllib3==1.26.19                                                                                  
urwid==2.6.15                                                                                     
us==3.1.1                                                                                         
uvicorn==0.27.0.post1                                                                             
validate-email==1.3                                                                               
w3lib==2.1.2                                                                                      
wcwidth==0.2.6                                                                                    
webdriver-manager==4.0.2                                                                          
webencodings==0.5.1                                                                               
websocket-client==1.8.0                                                                           
websockets==10.4                                                                                  
Werkzeug==2.3.8                                                                                   
whatsapp-converter==0.6.4                                                                         
wheel==0.41.3                                                                                     
win10toast==0.9                                                                                   
win32-setctime==1.1.0                                                                             
wrapt==1.16.0                                                                                     
wsproto==1.2.0                                                                                    
XlsxWriter==3.2.0                                                                                 
xmltodict==0.11.0                                                                                 
yarg==0.1.9                                                                                       
yarl==1.9.4                                                                                       
zeep==4.2.1                                                                                       
zipp==3.17.0                                                                                      
zope.event==5.0                                                                                   
zope.interface==6.4.post2                                                                         
zstandard==0.23.0                                                                                 

### What's your operating system?

Windows 11

### Are you using a separate virtual environment?

No

### Expected behavior

just for the import statement "scrapling.default" to work

### Actual behavior (Remember to use `debug` parameter)

No module named 'scrapling.default'

### Steps To Reproduce

1. open a new folder
2. new venv
3. install scrapling

**Comment by D4Vinci** [comment]
Hi mate, do this instead:
```python
from scrapling.defaults import Fetcher, StealthyFetcher, PlayWrightFetcher
```
It was a typo in the README page I will fix it right now. Thanks again!
