### ISSUE TITLE
LeakWarning: When using a proxy, it is heavily recommended that you pass `geoip=True`.

### ISSUE THREAD

**Issue by proxseas** [D4Vinci/Scrapling#24]
### Have you searched if there an existing issue for this?

- [X] I have searched the existing issues

### Python version (python --version)

3.12.7

### Scrapling version (scrapling.__version__)

0.2.8

### Dependencies version (pip3 freeze)

aiofiles==24.1.0
aiohappyeyeballs==2.4.3
aiohttp==3.11.7        
aiohttp_socks==0.9.1   
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
argcomplete==3.5.1
attrs==24.2.0
Brotli==1.1.0
browserforge==1.2.1
camoufox==0.4.8
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
colorama==0.4.6
cryptography==43.0.3
cssselect==1.2.0
defusedxml==0.7.1
distro==1.9.0
filelock==3.16.1
frozenlist==1.5.0
geoip2==4.8.1
greenlet==3.1.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.7
httpx==0.28.0
hyperframe==6.0.1
idna==3.10
jiter==0.8.0
kaitaistruct==0.10
language-tags==1.2.0
lxml==5.3.0
markdown-it-py==3.0.0
maxminddb==2.6.2
mdurl==0.1.2
multidict==6.1.0
numpy==2.1.3
orjson==3.10.12
outcome==1.3.0.post0
packaging==24.1
pipx==1.7.1
platformdirs==4.3.6
playwright==1.48.0
propcache==0.2.0
pyasn1==0.6.1
pycparser==2.22
pydantic==2.10.2
pydantic_core==2.27.1
pydivert==2.1.0
pyee==12.0.0
Pygments==2.18.0
pyOpenSSL==24.2.1
pyparsing==3.2.0
pyperclip==1.9.0
PySocks==1.7.1
python-socks==2.5.3
PyYAML==6.0.2
rebrowser_playwright==1.48.100
requests==2.32.3
requests-file==2.1.0
rich==13.9.4
scrapling==0.2.8
screeninfo==0.8.1
setuptools==75.6.0
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.6
tldextract==5.1.3
tqdm==4.67.1
trio==0.27.0
trio-websocket==0.11.1
typing_extensions==4.12.2
ua-parser==1.0.0
ua-parser-builtins==0.18.0
undetected-chromedriver==3.5.4
urllib3==2.2.3
userpath==1.9.2
w3lib==2.2.1
websockets==14.1
wsproto==1.2.0
yarl==1.18.0
zstandard==0.23.0

### What's your operating system?

Windows 10

### Are you using a separate virtual environment?

Yes

### Expected behavior

I should be able to pass the `geoip=True` arg to Camoufox through scrapling. Then it would not show the warning.

### Actual behavior (Remember to use `debug` parameter)

I'm using proxies, so I installed camoufox using `pip install -U 'camoufox[geoip]'`. This was in the documentation on their website. I looked into how to pass in this arg through scrapling and it is not currently being done. I would have to write my own wrapper to make it possible to pass this.

Currently, any time I use scrapling/camoufox with proxies, it will show this warning.

As a side point, `allow_webgl=True` something I can pass in, so I think the geoip arg should be handled similarly.

### Steps To Reproduce

Install scrapling / camoufox in a new virtual env:

- pip install -U 'camoufox[geoip]'
- pip3 install scrapling
- camoufox fetch
- camoufox fetch --browserforge

`from scrapling import StealthyFetcher

url='your url'
proxy='your proxy'

fetcher = StealthyFetcher()
res= fetcher.fetch(url, proxy)`

**Comment by D4Vinci** [comment]
Thanks, mate. It will be added to the next version. It's currently on the dev branch, but it should be ready in the next few days.

**Comment by D4Vinci** [comment]
Added with 0.2.9 I just released

**Comment by proxseas** [comment]
Fantastic. That warning was really annoying.
